export const PROJECTS = [
  {
    name: 'Consuming api of dev.to',
    description: 'projects.devto',
    language: 'Vue',
    stars: 1,
    forks: 0,
    url: 'https://github.com/addier94/my_web_site_client',
  },
  {
    name: 'countries info',
    description: 'projects.countries',
    language: 'React',
    stars: 5,
    forks: 2,
    url: 'https://github.com/addier94/countries-api',
    demo: 'https://addier94.github.io/countries-api',
  },
  {
    name: 'djeventsbo.vercel.app',
    description: 'projects.djeventsbo',
    language: 'React',
    stars: 7,
    forks: 1,
    url: 'https://github.com/addier94/djeventsbo-next',
    demo: 'https://djeventsbo.vercel.app',
  },
  {
    name: 'eccogamme.netlify.app',
    description: 'C-commerce of games, with more common functionality ',
    language: 'React',
    stars: 0,
    forks: 0,
    url: 'https://github.com/addier94/eccogame-next',
    demo: 'https://eccogame.netlify.app/',
  },
]
